### ISSUE TITLE
Observation Dependent Actions don't pass test

### ISSUE THREAD

**Issue by Zentrik** [JuliaPOMDP/POMDPTesting.jl#15]
In this line actions is called without the observation so an error is thrown, https://github.com/JuliaPOMDP/POMDPTesting.jl/blob/89791068da0e18d40a1bf78f891eb1ad5a9f60cc/src/model.jl#L36

I've defined actions like this 
```julia
𝒜 = function (belief)
    if sum(currentobs(b)) < params.max_flips
        return [FLIPₐ, FAIR, CHEATER]
    else
        return [FAIR, CHEATER]
    end
end
```
which I believe is the correct way of defining it.

**Comment by zsunberg** [comment]
Your definition seems correct. In order to pass the `has_consistent_transitions` test, you need to also define a method of the `actions` function that returns *all* of the actions if it does not get a belief argument. You can do that with an optional belief argument, something like:
```julia
𝒜 = function (belief=nothing)
    if isnothing(belief) || sum(currentobs(b)) < params.max_flips # note that I changed this line
        return [FLIPₐ, FAIR, CHEATER]
    else
        return [FAIR, CHEATER]
    end
end
```

**Comment by Zentrik** [comment]
Thanks, perhaps the documentation at https://github.com/JuliaPOMDP/POMDPs.jl/blob/7914ec92d8faf145513f4f9f2f8aa767019d722b/docs/src/def_pomdp.md?plain=1#L143 should be updated. QuickPOMDP does have a note about this but it only shows up on the dev documentation not the stable one.
